### ISSUE TITLE
下载百度云慢，修改aria2.conf没效果

### ISSUE THREAD

**Issue by brucmao** [jae-jae/Camtd#12]
我电信200M的，下载百度云只有1.2M/s左右，
max-connection-per-server=16  修改为 256
min-split-size=1M  修改为256K

修改没法运行了aria了，在插件里面暂停任务，也不能修改，是不是要自己编译啊，能分享个编译好的aria2么
![snipaste20180616_141205.png](https://i.loli.net/2018/06/16/5b24aaa7393bf.png)

**Comment by jae-jae** [comment]
Aria2手动编译教程：[https://www.easegamer.com/?p=483](https://www.easegamer.com/?p=483)
