### ISSUE TITLE
右键send to aria2 无效

### ISSUE THREAD

**Issue by luoluomeng** [jae-jae/Camtd#13]
Camtd版本:从chrome store上安装的1.4
Chrome版本:67.0.3396.87 (Official Build) (64-bit)
之前只可以用的,貌似自从chrome更新到某个版本之后就不可以了

**Comment by luoluomeng** [comment]
发现要使用这个功能需要在Chrome插件管理里面接管系统下载的设置里配置RPC，能否和插件内部的RPC配置整合？

**Comment by YYK19911212** [comment]
我也遇到这个问题了，连线正常，也有绿色的数字显示当前下载任务数，就是无法右键推送下载

**Comment by luoluomeng** [comment]
@YYK19911212 我找到解决办法了，在cheome的插件设置里面打开接管系统下载，配置一下RPC，然后再关闭接管系统下载，然后就可以了，插件自己的配置不会对右键功能生效

**Comment by jae-jae** [comment]
在插件图标上鼠标右键->选项->配置Aria2

**Comment by linweifu** [comment]
@luoluomeng @jae-jae 谢谢，碰到同样的问题，配置有两处地方。

**Comment by qhgary** [comment]
> Camtd版本:从chrome store上安装的1.4
> Chrome版本:67.0.3396.87 (Official Build) (64-bit)
> 之前只可以用的,貌似自从chrome更新到某个版本之后就不可以了

我也碰到同样的问题，请问如何解决的？

**Comment by luoluomeng** [comment]
> > Camtd版本:从chrome store上安装的1.4
> > Chrome版本:67.0.3396.87 (Official Build) (64-bit)
> > 之前只可以用的,貌似自从chrome更新到某个版本之后就不可以了
> 
> 我也碰到同样的问题，请问如何解决的？

上面有解决办法
