### ISSUE TITLE
支持 FireFox

### ISSUE THREAD

**Issue by xfoxfu** [jae-jae/Camtd#17]
FireFox 新版本的 WebExtension API 与 Chrome 相差无几，希望能够支持 FireFox。

**Comment by lonelykid** [comment]
😭，看来作者是没时间弄的了...firefox上现有的工具老是出错

**Comment by sleep39** [comment]
firefox可以用Aria2 Download Manager Integration，简单改一下就能愉快使用了。
@lonelykid

**Comment by lonelykid** [comment]
@sleep39 不知道是firefox api的问题，还是作者实现不同，总之是抓取有点问题

**Comment by sleep39** [comment]
我用的时候没遇到过，不清楚你说的问题。
´∀`
@lonelykid
