### ISSUE TITLE
希望能支持导入ariang的设置

### ISSUE THREAD

**Issue by rhjdvsgsgks** [jae-jae/Camtd#22]
rt，因为从手机上看这个插件的ui和ariang简直一模一样，所以就产生了这种想法

**Comment by jae-jae** [comment]
这个项目就是基于AriaNg的

**Comment by rhjdvsgsgks** [comment]
@jae-jae 但ariang的配置导入导出功能不见了，不知道是版本过老还是被阉割掉了
