### ISSUE TITLE
无法接管 vivaldi 下载

### ISSUE THREAD

**Issue by EdenHell** [jae-jae/Camtd#23]
如题，不过 send to aria2 可以使用
vivaldi 也是 blink 内核，希望能够得到支持

*系统：manjaro (kernel 4.14.71-1) x64*
*浏览器：Vivaldi | 1.15.1147.64 (Stable channel) （64 位）*

**Comment by EdenHell** [comment]
发现其实可以的

**Comment by Remonli** [comment]
win64 , vivaldi 2.4 不能接管.
